language:
  - cpp
notifications:
  email:
    on_success: never
    on_fail: always
git:
  depth: 1
cache:
  - ccache
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - g++-7
        - ninja-build
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - os: osx
    osx_image: xcode9.4
before_install:
  - mkdir -p $PWD/install/bin
  - ls -lh $PWD/install
  - export PATH="$PWD/install/bin:$PATH"
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install ninja bats ccache; export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "${MATRIX_EVAL}"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O cmake.sh https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh; sudo sh cmake.sh --skip-license --exclude-subdir --prefix=$PWD/install; fi
script:
  - cmake --version
  - ./build.sh -p $PWD/install
  - cd _build && ninja package && sudo ninja install && cd ..
  - bats --version
  - bats Test
deploy:
  - provider: releases
    api_key:
      secure: cU68PSZVlgTVNuSWBj7mjDbReYTl9a4MZnbNWYgUkQ67DBBz9YLxyTKj/MjQguvcIUSoSu2HsiZvOmGe6xifWqu5a9YNWW6NKAYJS4S/ZQSL2aFwPw7lkkVjOX0aA/5UUnhbBXlMsC/3f7ZIL9cGtmeC5nh83yTnWigSaSbhXvkc3MlxGzZoQ3evhKly/W8Q9dzIC5vzu3ChdwNaDtDtRQAgKT68QUR0eNMGZ9XsxNhNVW0KQ7H8YExSBZxhdJOl+cxWXpsccL5cYUpVwumOFouAtbIxZ4dT9noE8KbcOIEyyAWZy3JITTYXUFxsxF6e58RgZOeV77X2wP+6q1lURmQ/D2blzj2zCIgINcW3x+yw/2K9KK1e/tckYnENGjyLg//HyV878zFqxInhvIaqNJ9XaALi1JAY7rFYjWHmsWv8b9J4p8FDFe7BAo0U95fqLTEC83l9lAcSHw27jUWHYA6PsljLKXpS/s1OEt6McJu+NMmw9+TB+qx181CM6kgGfvUnfFgIDZHT70ZeN3IZrxwHQcJ2z8YrY4OQ0xr96X40RwUkiZOjFkhUPCJAYwP/99Vf6hZAV6Lj31yGJOXR23A7oQuBm9kG3M3hIRT7XN8vqJW+eRu7KV7xOImRKprWwhbUzakTpPZ6gOS4RhE6yFTUYhARcN7duz6l8ZazKLQ=
    skip_cleanup: true
    file_glob: true
    file: cmake_build/QUIT-*-Darwin.tar.gz
    on:
      condition: $TRAVIS_OS_NAME = osx
      repo: spinicist/QUIT
      tags: true
  - provider: releases
    api_key:
      secure: cU68PSZVlgTVNuSWBj7mjDbReYTl9a4MZnbNWYgUkQ67DBBz9YLxyTKj/MjQguvcIUSoSu2HsiZvOmGe6xifWqu5a9YNWW6NKAYJS4S/ZQSL2aFwPw7lkkVjOX0aA/5UUnhbBXlMsC/3f7ZIL9cGtmeC5nh83yTnWigSaSbhXvkc3MlxGzZoQ3evhKly/W8Q9dzIC5vzu3ChdwNaDtDtRQAgKT68QUR0eNMGZ9XsxNhNVW0KQ7H8YExSBZxhdJOl+cxWXpsccL5cYUpVwumOFouAtbIxZ4dT9noE8KbcOIEyyAWZy3JITTYXUFxsxF6e58RgZOeV77X2wP+6q1lURmQ/D2blzj2zCIgINcW3x+yw/2K9KK1e/tckYnENGjyLg//HyV878zFqxInhvIaqNJ9XaALi1JAY7rFYjWHmsWv8b9J4p8FDFe7BAo0U95fqLTEC83l9lAcSHw27jUWHYA6PsljLKXpS/s1OEt6McJu+NMmw9+TB+qx181CM6kgGfvUnfFgIDZHT70ZeN3IZrxwHQcJ2z8YrY4OQ0xr96X40RwUkiZOjFkhUPCJAYwP/99Vf6hZAV6Lj31yGJOXR23A7oQuBm9kG3M3hIRT7XN8vqJW+eRu7KV7xOImRKprWwhbUzakTpPZ6gOS4RhE6yFTUYhARcN7duz6l8ZazKLQ=
    skip_cleanup: true
    file_glob: true
    file:
      - cmake_build/QUIT-*-Linux.tar.gz
      - cmake_build/QUIT-*-Linux.deb
    on:
      condition: $TRAVIS_OS_NAME = linux
      repo: spinicist/QUIT
      tags: true
