trigger:
- master
jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - bash: brew update; brew install ninja bats;
    displayName: 'Install tools from Brew'
  - bash: ./build.sh -j 4 -p "$PWD/install" -i
    displayName: 'Build'
  - bash: export PATH="$PWD/install/bin:$PATH"; echo $PATH; pwd; which qinewimage; ls "$PWD/install/bin"; bats Test/
    displayName: 'Run Tests'
